// ─────────────────────────────────────────────────────────────
// TalkBingo demo — question pool pulled from the PRODUCTION server
// (public.questions, project jmihbovtywtwqdjrmuey).
// Truth   = { q: prompt, chips: [tailored quick-tap answers] }
// Balance = { q: prompt, a: choiceA, b: choiceB }
// The board rotates through these (cell seed % length).
// ─────────────────────────────────────────────────────────────
window.__TB_TRUTH = {
  ko: [
    { q: "영통 중 잠든 적 있어? 어떻게 됐어?", chips: ["코골이 녹음당함","다음 날 캡처봄","같이 잠듦"] },
    { q: "연인이 아껴둔 디저트 먹었을 때 솔직 반응?", chips: ["보상받기 모드","잠깐 토라짐","그냥 넘어감"] },
    { q: "익숙한 취미 vs 새로운 탐험, 나의 선택은?", chips: ["깊게 파기","넓게 경험하기"] },
    { q: "둘이 다이어트 깬 핑계 단골 멘트?", chips: ["오늘만","운동 했잖아","내일부터"] },
    { q: "장기 연애의 비결은 뭐라고 생각해?", chips: ["편안함","신뢰","적당한 무관심"] },
    { q: "월요일 아침에 진짜 한 짓 하나만 말해줘!", chips: ["알람 다 끄기","5분만 더","맨발로 뛰쳐"] },
    { q: "애인이 몰래 찍은 사진 발견하면?", chips: ["당장 지우라기","같이 웃음","은근 좋아함"] },
    { q: "빨리 자라 잔소리 들으면 어떻게 해?", chips: ["끈 척한다","이불 속에서","진짜 잔다"] },
    { q: "혹시 가족한테 택배 부탁할 때 미안한 적 있어?", chips: ["좀 미안함","당연한 거지","눈치 보임"] },
    { q: "가장 즐겨 만드는 나만의 간편 요리는?", chips: ["간장계란밥","라면","김치볶음밥","토스트"] },
    { q: "학창시절 제일 큰 흑역사는?", chips: ["졸업사진","장기자랑","고백 실패"] },
    { q: "권태기를 느낀 적은?", chips: ["한 번 쯤","전혀 없음","싸울 때 잠깐"] },
    { q: "엄마가 내 간식 버렸을 때 진짜 속마음은?", chips: ["허무 대폭발","유통기한 빌런","그러려니 포기"] },
    { q: "야식으로 제일 자주 시키는 건?", chips: ["치킨","라면","떡볶이"] },
    { q: "배달 실망했을 때 너 진짜 어떡함?", chips: ["다 먹음","별점 테러","조용히 안 시킴"] },
    { q: "주말 끝나면 가족이랑 뭐 하면서 보내?", chips: ["같이 TV 봄","각자 폰만 함","밥만 같이"] },
    { q: "요즘 컨디션은 괜찮은지 궁금하네?", chips: ["환절기라 피곤한 요","부쩍 피곤해 보이는","스트레스 받는 일이"] },
    { q: "혹시 새벽 감성으로 세운 웃긴 계획 있어?", chips: ["갑자기 퇴사 결심","사업 아이디어","갓생 설계"] },
    { q: "날씨 핑계로 엄살 부린 적, 나는?", chips: ["쑤시는 무릎","심해지는 미세먼지 알레르기"] },
    { q: "소개팅 카페에서 뭐 시켜?", chips: ["커피","주스","디저트 세트"] },
    { q: "급 만남에서 절대 실패 없는 메뉴는?", chips: ["고기","치킨","분식"] },
    { q: "연인한테 까먹은 말 뭐 있었어?", chips: ["깜짝 계획","고마운 말","약속 변경"] },
    { q: "냉장고 남은 거로 만든 야식 최고 조합은?", chips: ["김치 라면","계란밥","남은 반찬"] },
    { q: "새롭게 도전해보고 싶은 분야는?", chips: ["스포츠","예술","요리","사업"] },
    { q: "고민이 있을 때, 제일 먼저 누구에게 말하어?", chips: ["절친","엄마","해결사","나 자신"] },
    { q: "올해 가장 기대되는 변화는?", chips: ["몸매 변화","통장 잔고","연애 상태"] },
    { q: "월요 아침 응원 너의 방식은?", chips: ["장문 응원톡","화이팅 한 줄","모닝콜 깨움"] },
    { q: "가장 편안하게 느껴지는 순간은?", chips: ["비 오는 날","주말 아침","잠들기 전"] },
    { q: "작년 여름 옷 꺼냈다가 현실 직면한 적 있어?", chips: ["반팔 안 맞음","조용히 접음","다이어트 결심"] },
    { q: "갑자기 반팔인 날 너 첫 반응은?", chips: ["헐 진짜?","옷장 멘붕","신난다"] },
    { q: "네가 퇴근 후 집에 오면, 제일 먼저 하는 일은?", chips: ["옷 갈아입기","눕기","손 씻기","냉장고 확인"] },
    { q: "마지막 연애, 헤어진 이유는?", chips: ["성격 차이","환승 당함","장거리 연애"] },
    { q: "머리 지끈거릴 때, 나만의 특별한 해결책은?", chips: ["찬물 세수","당 충전","명상"] },
    { q: "혹시 명절에 배달 시키자고 해본 적 있어?", chips: ["직접 제안","눈치만 봄","가족이 먼저"] },
    { q: "여름 이불로 언제 바꿔? 가족이랑 타이밍 맞아?", chips: ["벌써 바꿈","7월까지 버팀","겨울 이불째"] },
    { q: "오늘 하루 속에서 예상치 못한 작은 행복을 하나 정한다면?", chips: ["버스 바로 옴","칭찬 받음","공돈 생김"] },
    { q: "둘만의 추억 노래 한 곡 떠올리면?", chips: ["첫 데이트 곡","차 안에서 들은 곡","노래방 듀엣곡"] },
    { q: "지친 몸 달래는 나만의 최고의 방법은?", chips: ["사우나","마사지","넷플릭스"] },
    { q: "술 마신 다음 날 제일 힘든 건?", chips: ["심한 두통","늘어짐","속 안 좋음"] },
    { q: "자기 전 애인 먹방 사진 받으면?", chips: ["바로 따라 시킴","참고 그냥 잠","사진 그만 보내라기"] },
    { q: "목소리 읽는 기술 보면 앞으로 어떨 것 같아?", chips: ["SF 영화 연상","미래 직업","기술의 명암"] },
    { q: "인맥 관리의 핵심은?", chips: ["적당한 거리","연락","경조사"] },
    { q: "가족 행사 사진 올리기 전 너의 진짜 고민?", chips: ["초상권 걱정","친척 반응 부담","그냥 귀찮음"] },
    { q: "약속에 늦었을 때 제일 미안했던 적은?", chips: ["기념일 지각","기다리게 한 시간","핑계 댄 순간"] },
    { q: "더운 날 데이트 너의 진짜 픽?", chips: ["영화관","백화점 구경","집 데이트"] },
    { q: "데이트 중 콧물 터진 흑역사 있어?", chips: ["화장 다 지워짐","연인이 당황함","그래도 웃어줬"] },
    { q: "가족 앨범에서 당장 없애고 싶은 사진 뭐야?", chips: ["버섯머리 사진","유치원 연극컷","치아 빠진 돌컷"] },
    { q: "너한테 에너지원이 되는 것은 뭐야?", chips: ["밥","잠","월급","사랑"] },
    { q: "야식 유혹 못 참은 순간 언제야?", chips: ["다이어트 첫날","스트레스 폭발","먹방 본 직후"] },
    { q: "한정판 간식 지키는 너만의 방법은?", chips: ["이중봉지 위장","방에 따로 보관","단톡에 미리경고"] }
  ],
  en: [
    { q: "Ever fallen asleep on a video call? What happened?", chips: ["snoring got recorded","saw screenshot next day","both fell asleep"] },
    { q: "Partner ate your saved dessert — your honest reaction?", chips: ["demand-compensation mode","brief sulk","just let it slide"] },
    { q: "Stick to familiar hobbies or explore new ones?", chips: ["Go deep","experience widely"] },
    { q: "Your go-to excuse for breaking the couple diet?", chips: ["just today","but we worked out","starting tomorrow"] },
    { q: "What do you think is the secret to a long-term relationship?", chips: ["Comfort","trust","a little indifference"] },
    { q: "Tell me one real thing you did this Monday morning!", chips: ["killed all alarms","5 more minutes","ran out barefoot"] },
    { q: "When you find a secret cringe photo your partner took, you?", chips: ["Demand delete","Laugh together","Secretly love it"] },
    { q: "When parents nag you to sleep, what do you do?", chips: ["Fake it off","Hide in covers","Actually sleep"] },
    { q: "Have you ever felt bad asking family to receive a package?", chips: ["A little sorry","It's normal","Feel awkward"] },
    { q: "What's your go-to quick and easy recipe?", chips: ["Soy Sauce Egg Rice","Ramen","Kimchi Fried Rice","Toast"] },
    { q: "Biggest embarrassing moment from school days?", chips: ["Graduation photo","Talent show","Failed confession"] },
    { q: "Have you ever felt like we were in a rut?", chips: ["Once or twice","Never","Briefly when we fight"] },
    { q: "Mom tossed your snack — your honest inner voice?", chips: ["pure devastation","expiration-date villain","just give up and accept it"] },
    { q: "What do you order most for late-night snacks?", chips: ["chicken","ramyeon","tteokbokki"] },
    { q: "Delivery let you down — what do you actually do?", chips: ["eat it anyway","drop a 1-star","quietly stop ordering"] },
    { q: "How do you spend the end of the weekend with family?", chips: ["watch TV together","everyone on phones","just share a meal"] },
    { q: "How's your health been holding up?", chips: ["seasonal tiredness","looking worn out","stressful times"] },
    { q: "Ever made a ridiculous life plan at 3 a.m.?", chips: ["suddenly decided to quit","a startup idea","a whole 'best life' blueprint"] },
    { q: "Have you ever exaggerated an ailment because of the weather?", chips: ["Aching knees","Worsening fine dust allergy"] },
    { q: "What do you order at a cafe on a blind date?", chips: ["coffee","juice","dessert set"] },
    { q: "What's a fail-safe menu for a last-minute hangout?", chips: ["meat","chicken","snack food"] },
    { q: "What's something you forgot to tell your partner?", chips: ["a surprise plan","a thank you","a schedule change"] },
    { q: "Best late-night combo you made with fridge leftovers?", chips: ["kimchi ramen","egg rice","leftover sides"] },
    { q: "What new field are you interested in exploring?", chips: ["Sports","art","cooking","business"] },
    { q: "When something's bothering you, who do you talk to first?", chips: ["My Best Friend","Mom","My Go-To Problem Solver","Myself"] },
    { q: "What change are you most hoping for this year?", chips: ["Body transformation","bank balance","relationship status"] },
    { q: "Monday morning — how do you cheer them up?", chips: ["long cheer text","just one 'fighting!'","a wake-up call"] },
    { q: "When do you feel most relaxed?", chips: ["Rainy days","weekend mornings","before sleep"] },
    { q: "Ever face reality pulling out last summer's clothes?", chips: ["Tee won't fit","Quietly refold","Diet vow"] },
    { q: "Suddenly short-sleeve weather — your first reaction?", chips: ["wait, really?","closet meltdown","I love this"] },
    { q: "When you get home after work, what's the first thing you do?", chips: ["Change Clothes","Flop on the Couch","Wash Hands","Raid the Fridge"] },
    { q: "Last relationship, why did you break up?", chips: ["Personality differences","Got cheated on","Long distance"] },
    { q: "Your go-to move when your head's pounding?", chips: ["Cold water splash","sugar rush","meditation"] },
    { q: "Ever suggested ordering delivery for the holidays?", chips: ["suggested it","just hinted","family did first"] },
    { q: "When do you switch to summer bedding? Same timing as family?", chips: ["Already did","Hold till July","Still winter one"] },
    { q: "Name one small unexpected happiness from today?", chips: ["Bus Came Right Away","Got a Compliment","Found Free Money"] },
    { q: "Pick one song that's just yours as a couple — what is it?", chips: ["the first-date song","one we played in the car","a karaoke duet"] },
    { q: "Best way to soothe a tired body?", chips: ["Sauna","Massage","Netflix"] },
    { q: "What's the hardest part about the day after drinking?", chips: ["Terrible headache","feeling lazy","upset stomach"] },
    { q: "Get a food pic from your partner before bed?", chips: ["Order the same right away","Endure and sleep","Beg them to stop"] },
    { q: "Where do you think voice-reading tech is headed?", chips: ["sci-fi vibes","future careers","pros and cons"] },
    { q: "Key to managing relationships?", chips: ["Appropriate distance","keeping in touch","life events"] },
    { q: "Real worry before posting family-event photos?", chips: ["Image-rights concern","Relatives' reactions","Just too much work"] },
    { q: "When was the time you felt most sorry for being late?", chips: ["late on anniversary","hours of waiting","making excuses"] },
    { q: "Hot-day date — your real top picks?", chips: ["Movie theater","Department store browsing","Stay-in date"] },
    { q: "Ever had an embarrassing runny nose moment on a date?", chips: ["makeup all ruined","partner was caught off guard","still laughed it off"] },
    { q: "Which photo in the family album do you most want gone?", chips: ["the bowl-cut one","the preschool play one","the toothless birthday one"] },
    { q: "What gives you energy?", chips: ["Food","Sleep","Paycheck","Love"] },
    { q: "When did the late-night snack temptation win?", chips: ["Day 1 of diet","Stress blowout","Right after mukbang"] },
    { q: "Your own way of guarding a limited-edition snack?", chips: ["double-bag camouflage","store it in your room","send a heads-up in the chat"] }
  ]
};

window.__TB_BALANCE = {
  ko: [
    { q: "함께 일하고 싶은 동료 스타일은?", a: "농땡이꾼", b: "투명인간 취급" },
    { q: "같이 OTT 볼 때 너는?", a: "로맨스 정주행", b: "액션 한 편 깔끔" },
    { q: "내 옛 일기장 형제가 읽으면?", a: "빼앗아 감춘다", b: "같이 읽고 웃기" },
    { q: "부모님 배달앱 첫 주문 때, 나는?", a: "직접 도와드린다", b: "알아서 하시게 둔다" },
    { q: "야식 먹고 다음 날 후회하면, 나는?", a: "다신 안 먹는다 다짐", b: "또 먹을 거란 걸 앎" },
    { q: "처음 보는 음식 나오면, 뭐부터 하는 편?", a: "바로 사진 찍기", b: "바로 냄새 맡기" },
    { q: "컨디션 꽝일 때, 나만의 특효약은?", a: "약 먹고 푹 자기", b: "맛있는 배달음식" },
    { q: "우리 장거리 연애 잘해낼 수 있을까?", a: "할 수 있을 것 같아", b: "걱정돼" },
    { q: "데이트 중 배고프면, 나는?", a: "솔직히 말한다", b: "참고 집중한다" },
    { q: "연인에게 혼자 있고 싶다고 하면?", a: "솔직히 말한다", b: "돌려서 말한다" },
    { q: "엄마가 손님 앞 옛날 얘기 시작?", a: "웃으며 맞장구", b: "방으로 도망친다" },
    { q: "스타일 고민할 때, 참고하는 건?", a: "주변 피드백", b: "내 직감" },
    { q: "부모님 음주, 더 걱정되는 점은?", a: "술버릇과 주사", b: "눈에 띄는 건강 악화" },
    { q: "시험 기간 내 스타일은?", a: "도서관에서 혼자 집중", b: "카페에서 친구랑 같이" },
    { q: "독립한다면, 어느 쪽이 더 나아?", a: "혼자 살기", b: "친구들 살기" },
    { q: "통화 중 연인이 배고프다 하면?", a: "배달 시켜준다", b: "같이 시켜 먹자" },
    { q: "어느 쪽이 더 하고 싶어?", a: "유튜브 채널 운영", b: "팟캐스트 운영" },
    { q: "퇴근 후 연락, 어디까지 괜찮은?", a: "긴급 회의 링크", b: "잡담 톡" },
    { q: "애인 친구 이름 까먹으면?", a: "솔직히 미안 고백", b: "아는 척 버팀" },
    { q: "사귄 초기 사진 발견하면 나는?", a: "같이 보며 추억팔이", b: "혼자 몰래 감상" },
    { q: "지금 더 끌리는 휴식은?", a: "조용한 낮잠", b: "뇌 빼고 숏폼 정주행" },
    { q: "같이 다이어트 약속, 깨면 나는?", a: "바로 자수함", b: "끝까지 모른 척" },
    { q: "배달 음식 실망, 어떡함?", a: "별점 1개 박기", b: "조용히 안 시키기" },
    { q: "연인이 추우면 외투 어떻게 해?", a: "바로 벗어준다", b: "나도 춥다고 함" },
    { q: "중요한 선택을 앞두고 나를 더 방해하는 것은?", a: "훈수 두는 지인들", b: "먹통 된 와이파이" },
    { q: "어느 쪽이 덜 불편한 지인이야?", a: "거울 보면 무조건 셀카", b: "음악 들으면 무조건 춤" },
    { q: "어느 쪽이 덜 나빠?", a: "여행 중 길 잃기", b: "여행 중 소매치기" },
    { q: "유행 영상보다 철학 책 읽기에 더 끌려?", a: "철학 책", b: "유행 영상" },
    { q: "잠 안 올 때 나는?", a: "폰 보다 잠듦", b: "불 끄고 버팀" },
    { q: "지친 날 친구가 부탁을 해올 때 나의 선택은?", a: "투덜대며 들어줌", b: "단호하게 거절" },
    { q: "다이어트 중 연인 야식 제안, 너는?", a: "같이 무너지자", b: "나만 참는다" },
    { q: "이상형과 매일 싸운다면, 그래도 만날까?", a: "맞춰간다", b: "갈아탄다" },
    { q: "출근 인사, 너의 스타일은?", a: "끝까지 끌어안기", b: "깔끔하게 손 인사" },
    { q: "더 마음이 가는 장소는?", a: "활기찬 노래방", b: "활기찬 운동장/공원" },
    { q: "연인 땀 냄새, 너는?", a: "솔직히 말한다", b: "데오도란트 선물" },
    { q: "내가 부모라면, 받고 싶은 선물 스타일은?", a: "실용적 현금 봉투", b: "직접고른 선물" },
    { q: "가족에게 들으면 섭섭하고 싫은 말은?", a: "너 예민해", b: "그럴 줄 알았다" },
    { q: "바빠서 뜸했던 연인이 연락 오면?", a: "반갑다", b: "서운하다" },
    { q: "일요일 저녁 월요병 오면 나는?", a: "유튜브로 도피", b: "일찍 자려 노력" },
    { q: "작년 반팔 안 맞을 때 너는?", a: "옷이 줄었다 우김", b: "쿨하게 사이즈업" },
    { q: "엄마 사진 또 흔들렸어, 너는?", a: "찍는 법 알려드리기", b: "그냥 받고 넘기기" },
    { q: "갑자기 1억이 생긴다면 어디에 쓸?", a: "빚 청산 & 장비빨", b: "재테크 & 창업" },
    { q: "어느 쪽이 덜 불편해?", a: "방귀 = 노크 소리", b: "방귀 = 장미향" },
    { q: "지금 나를 더 잘 표현하는 말은?", a: "여전히 성장 중", b: "성숙한 지금" },
    { q: "부모님과 에어컨 협상이면?", a: "참고 선풍기", b: "몰래 에어컨" },
    { q: "데이트 사진 보정, 우리는?", a: "보정은 셀프 케어", b: "있는 그대로가 진리" },
    { q: "딸이 있어서 정말 든든하다고 느낄 때는?", a: "센스 있는 선물", b: "조용한 위로" },
    { q: "어느 쪽이 더 나아?", a: "국물 없는 음식만", b: "국물 있는 음식만" },
    { q: "여름 밤 적정 온도 너는?", a: "22도 냉동실파", b: "26도 적정파" },
    { q: "가치관 다른 동료와 해결법은?", a: "쟁점 논쟁", b: "다름 인정" }
  ],
  en: [
    { q: "What kind of coworker do you want to work closely with?", a: "Slacker", b: "Vanishing act" },
    { q: "Watching together on a streaming app — your pick?", a: "binge a romance series", b: "one clean action movie" },
    { q: "If your sibling reads your old diary, you...", a: "snatch it and hide it", b: "read along and laugh" },
    { q: "When your parents try a delivery app for the first time?", a: "help them through it", b: "let them figure it out" },
    { q: "After regretting late-night snacking the next morning?", a: "Swear never again", b: "Know I'll do it again" },
    { q: "What do you usually do first when you see unfamiliar food?", a: "Take a photo right away", b: "Sniff it immediately" },
    { q: "What's your go-to cure when you're feeling terrible?", a: "Take meds, sleep lots", b: "Order yummy food" },
    { q: "Do you think we can make long-distance work?", a: "We can do it", b: "I'm worried" },
    { q: "When you get hungry during a date, what do you do?", a: "Say it honestly", b: "Hold it in and focus" },
    { q: "Telling your partner you want alone time?", a: "say it directly", b: "hint at it gently" },
    { q: "Mom starts old stories in front of guests?", a: "Smile and play along", b: "Escape to my room" },
    { q: "When figuring out your style, what do you rely on?", a: "feedback from others", b: "my own gut feeling" },
    { q: "What worries you more about parents drinking?", a: "Bad drinking habits", b: "Health decline" },
    { q: "What's your study style during exam week?", a: "Quiet library focus", b: "Cafe study buddies" },
    { q: "If you go solo, which sounds better?", a: "Living alone", b: "Living with pals" },
    { q: "If your partner says 'I'm hungry' on a call, you...", a: "order delivery for them", b: "order and eat together" },
    { q: "Which one would you rather do?", a: "Run a YouTube channel", b: "Run a podcast" },
    { q: "What's the best way to unwind after work?", a: "Urgent meeting link", b: "Casual chat" },
    { q: "Forget your partner's friend's name — you?", a: "Just fess up sorry", b: "Fake knowing it" },
    { q: "When you find early dating photos, you...", a: "reminisce together", b: "look at them alone" },
    { q: "Which chill break feels more tempting now?", a: "Quiet nap", b: "Scroll through shorts" },
    { q: "You broke a shared diet pact — you?", a: "confess right away", b: "play dumb forever" },
    { q: "Delivery flopped — what do you do?", a: "leave a 1-star", b: "quietly ghost the place" },
    { q: "If your partner's cold, what do you do with your jacket?", a: "give it right away", b: "say I'm cold too" },
    { q: "What distracts me more before an important decision?", a: "Nosy acquaintances", b: "Dead WiFi" },
    { q: "Which friend is easier to be around?", a: "mirror = selfie time", b: "music = instant dance" },
    { q: "Which one seems less bad?", a: "Getting lost", b: "Getting pickpocketed" },
    { q: "Does reading philosophy appeal to you more than viral videos?", a: "Philosophy book", b: "Viral videos" },
    { q: "Can't fall asleep — you?", a: "Scroll till you drop", b: "Lights off, tough it out" },
    { q: "When tired and a friend asks a favor, I?", a: "Help while complaining", b: "Firmly refuse" },
    { q: "Mid-diet, partner suggests a late-night snack — you?", a: "Cave in together", b: "I'll stay strong" },
    { q: "Would you still meet up if you fought with your ideal partner every day?", a: "Adjust accordingly", b: "Switch it up" },
    { q: "Saying bye before work — your style?", a: "Long clingy hug", b: "A clean wave goodbye" },
    { q: "Where do you feel most drawn?", a: "Lively karaoke room", b: "Energetic park/field" },
    { q: "Partner's sweat smell — you?", a: "Say it honestly", b: "Gift a deodorant" },
    { q: "As a parent, what gift style would you want?", a: "Cash in an Envelope", b: "A Hand-Picked Gift" },
    { q: "Which family comment stings more?", a: "too sensitive", b: "saw that coming" },
    { q: "When your busy partner finally texts back?", a: "just happy", b: "a bit hurt" },
    { q: "When Sunday-evening Monday-dread hits, you...", a: "escape into YouTube", b: "try to sleep early" },
    { q: "When last year's tee doesn't fit — your move?", a: "Claim it shrunk", b: "Just size up" },
    { q: "Mom shook the phone again — your move?", a: "Teach her how to shoot", b: "Just accept it" },
    { q: "Suddenly have 100M won — where does it go?", a: "clear debts + upgrade", b: "invest + start up" },
    { q: "Which feels less awkward?", a: "Passing gas = knocking", b: "Passing gas = rose scent" },
    { q: "Which phrase best describes me right now?", a: "Still growing", b: "Mature now" },
    { q: "Negotiating AC with your parents — you?", a: "Hold out with the fan", b: "Sneak the AC on" },
    { q: "Editing date photos — your stance?", a: "editing is self-care", b: "raw is the truth" },
    { q: "When do you feel really supported having a daughter?", a: "Cool gifts", b: "Quiet comfort" },
    { q: "Which one sounds better?", a: "No broth dishes only", b: "Only broth dishes" },
    { q: "Your ideal AC temp at night?", a: "22°C freezer mode", b: "26°C moderate setting" },
    { q: "Handling a clashing coworker?", a: "Debate the Issue Head-On", b: "Agree to Disagree" }
  ]
};
