// ─────────────────────────────────────────────────────────────
// TalkBingo demo — question pool pulled from the PRODUCTION server
// (public.questions, project jmihbovtywtwqdjrmuey) on 2026-06-13.
// Truth = question string. Balance = { q: prompt, a: choiceA, b: choiceB }.
// The board rotates through these (cell seed % length).
// ─────────────────────────────────────────────────────────────
window.__TB_TRUTH = {
  ko: [
    "하루 중 가장 행복한 시간은?",
    "차 타면 잠드는 데 몇 분 걸려?",
    "최근에 제일 관심이 가는 분야는?",
    "호감 가는 사람에게 제일 먼저 하는 행동은?",
    "절대 포기 못 하는 나만의 취향은?",
    "이불 교체 같은 집안일, 너는 미루는 편이야?",
    "비 올 때 너만의 감성 루틴 있어?",
    "요즘 자주 하는 생각은?",
    "요즘 성장을 위해 제일 중요한 건 뭐야?",
    "가족이 뜯어본 내 택배 뭐였어?",
    "살면서 가장 보람을 느끼는 활동은?",
    "일요일 저녁 우리 가족은 보통 뭐 해?",
    "맛집 사진 올릴 때 너의 진짜 속마음?",
    "더워서 약속 취소하고 싶었던 적, 언제가 제일 심했어?",
    "혹시 봄 산책 나가서 졸았던 적 있어?",
    "연인 사진 못 찍을 때 본심?",
    "에너지 바닥일 때 몸이 외치는 건?",
    "주말 데이트 끝나고 월요병 온 적?",
    "자기 전 폰 하다 생긴 웃긴 버릇 있어?",
    "최근 너를 설레게 한 새로운 도전은 뭐야?",
    "더운 날 약속 잡혔을 때 너는?",
    "꿈에서 나한테 서운했던 적 있어?",
    "연인이랑 다이어트하다 같이 무너진 순간?",
    "행인 사진 망했을 때 어떻게 해?",
    "요즘 내 마음은 어떤 상태?",
    "너무 심심할 때 하는 행동?",
    "올해 같이 하자고 한 거 중에 한 거 있어?",
    "목소리로 기분 맞추는 기술 본 적 있어?",
    "애인 택배 왔을 때 너 진짜 행동?",
    "벚꽃 명소 중에 최애 장소 있어?",
    "어젯밤에 기억나는 것은?",
    "야식으로 제일 자주 시키는 건?",
    "스트레스받으면 제일 먼저 하는 일은?",
    "상대 폰 불빛 때문에 잠 설쳤던 순간 있어?",
    "여름에 부모님께 챙겨드리고 싶은 거 뭐야?",
    "MBTI 관련 제일 기억에 남는 반응은?",
    "아껴뒀던 간식 먹혔을 때 제일 서러운 건?",
    "패스해도 되는데, 전 연인 연락에 흔들린 적 있어?",
    "부모님이 월요 아침 꼭 챙겨주시는 건?",
    "약속 카톡 읽씹당하면 너 어때?",
    "어른 앞에서 실언한 적 있어?",
    "평소 에어컨 몇 도로 틀어?",
    "최고의 숙면을 위해 네가 하는 루틴이 있다면?",
    "호감 가는 상대의 행동은?",
    "배달앱 메뉴 고르는 데 얼마 걸려?",
    "복잡한 머릿속을 평화롭게 만드는 치트키는?",
    "하루 중 가장 지치는 시간대는?",
    "약속 취소한 날 더 보고 싶어진 적 있어?",
    "가장 중요하다고 생각하는 나의 가치관은 뭐야?",
    "올여름 도전해보고 싶은 옷차림 있어?"
  ],
  en: [
    "Happiest time of the day?",
    "How many minutes does it take you to fall asleep in a car?",
    "What field has caught your interest lately?",
    "What's the first thing you do when you like someone?",
    "What's a personal preference you'll never give up?",
    "For chores like switching blankets, do you put it off?",
    "Do you have a personal rainy-day mood ritual?",
    "What's been on your mind lately?",
    "What's the most important thing for growth right now?",
    "What package did your family open without asking?",
    "What activities feel most rewarding in life?",
    "What does Sunday evening usually look like in your family?",
    "Real reason you post that hot-restaurant photo?",
    "When was the urge to cancel plans for heat the strongest?",
    "Have you ever dozed off on a spring walk, by any chance?",
    "Partner can't take good photos — your honest move?",
    "When your energy is rock bottom, what does your body crave?",
    "Ever got Monday blues after a weekend date?",
    "Any funny habit you've picked up from late-night scrolling?",
    "What new challenge has excited you recently?",
    "When plans land on a hot day, what do you do?",
    "Ever felt a little hurt at me because of a dream?",
    "Moment you and your partner broke the diet together?",
    "Stranger botched your photo — how do you handle it?",
    "What's my mood like lately?",
    "What do you do when you're super bored?",
    "Did you two do any of what you planned together?",
    "Have you seen that voice mood-reading tech on TV?",
    "Partner's package arrives — what do you actually do?",
    "Do you have a favorite cherry blossom spot?",
    "What do you remember from last night?",
    "What do you order most for late-night snacks?",
    "What's the first thing you do when you get stressed?",
    "Ever lost sleep over your partner's phone glow?",
    "What do you want to do for your parents in summer?",
    "What's the most memorable MBTI reaction you've experienced?",
    "What's the worst part when someone eats your saved snack?",
    "OK to pass — ever wavered when an ex reached out?",
    "What do your parents always give you on Monday mornings?",
    "Plans text was read-and-ignored — how do you take it?",
    "Have you ever blurted something out in front of elders?",
    "What temp do you usually set the AC at?",
    "Do you have a bedtime routine for the best sleep?",
    "What's an attractive trait in someone you like?",
    "How long do you spend picking a menu on a delivery app?",
    "What's your go-to for instant peace of mind?",
    "What's the most draining time of your day?",
    "Ever missed them more on the day you canceled?",
    "What's the most important personal value to you?",
    "Any outfit you want to try this summer?"
  ]
};

window.__TB_BALANCE = {
  ko: [
    { q: "함께 일하고 싶은 동료 스타일은?", a: "농땡이꾼", b: "투명인간 취급" },
    { q: "같이 OTT 볼 때 너는?", a: "로맨스 정주행", b: "액션 한 편 깔끔" },
    { q: "내 옛 일기장 형제가 읽으면?", a: "빼앗아 감춘다", b: "같이 읽고 웃기" },
    { q: "부모님 배달앱 첫 주문 때, 나는?", a: "직접 도와드린다", b: "알아서 하시게 둔다" },
    { q: "야식 먹고 다음 날 후회하면, 나는?", a: "다신 안 먹는다 다짐", b: "또 먹을 거란 걸 앎" },
    { q: "처음 보는 음식 나오면, 뭐부터 하는 편?", a: "바로 사진 찍기", b: "바로 냄새 맡기" },
    { q: "컨디션 꽝일 때, 나만의 특효약은?", a: "약 먹고 푹 자기", b: "맛있는 배달음식" },
    { q: "우리 장거리 연애 잘해낼 수 있을까?", a: "할 수 있을 것 같아", b: "걱정돼" },
    { q: "데이트 중 배고프면, 나는?", a: "솔직히 말한다", b: "참고 집중한다" },
    { q: "연인에게 혼자 있고 싶다고 하면?", a: "솔직히 말한다", b: "돌려서 말한다" },
    { q: "엄마가 손님 앞 옛날 얘기 시작?", a: "웃으며 맞장구", b: "방으로 도망친다" },
    { q: "스타일 고민할 때, 참고하는 건?", a: "주변 피드백", b: "내 직감" },
    { q: "부모님 음주, 더 걱정되는 점은?", a: "술버릇과 주사", b: "눈에 띄는 건강 악화" },
    { q: "시험 기간 내 스타일은?", a: "도서관에서 혼자 집중", b: "카페에서 친구랑 같이" },
    { q: "독립한다면, 어느 쪽이 더 나아?", a: "혼자 살기", b: "친구들 살기" },
    { q: "통화 중 연인이 배고프다 하면?", a: "배달 시켜준다", b: "같이 시켜 먹자" },
    { q: "어느 쪽이 더 하고 싶어?", a: "유튜브 채널 운영", b: "팟캐스트 운영" },
    { q: "퇴근 후 연락, 어디까지 괜찮은?", a: "긴급 회의 링크", b: "잡담 톡" },
    { q: "애인 친구 이름 까먹으면?", a: "솔직히 미안 고백", b: "아는 척 버팀" },
    { q: "사귄 초기 사진 발견하면 나는?", a: "같이 보며 추억팔이", b: "혼자 몰래 감상" },
    { q: "지금 더 끌리는 휴식은?", a: "조용한 낮잠", b: "뇌 빼고 숏폼 정주행" },
    { q: "같이 다이어트 약속, 깨면 나는?", a: "바로 자수함", b: "끝까지 모른 척" },
    { q: "배달 음식 실망, 어떡함?", a: "별점 1개 박기", b: "조용히 안 시키기" },
    { q: "연인이 추우면 외투 어떻게 해?", a: "바로 벗어준다", b: "나도 춥다고 함" },
    { q: "중요한 선택을 앞두고 나를 더 방해하는 것은?", a: "훈수 두는 지인들", b: "먹통 된 와이파이" },
    { q: "어느 쪽이 덜 불편한 지인이야?", a: "거울 보면 무조건 셀카", b: "음악 들으면 무조건 춤" },
    { q: "어느 쪽이 덜 나빠?", a: "여행 중 길 잃기", b: "여행 중 소매치기" },
    { q: "유행 영상보다 철학 책 읽기에 더 끌려?", a: "철학 책", b: "유행 영상" },
    { q: "잠 안 올 때 나는?", a: "폰 보다 잠듦", b: "불 끄고 버팀" },
    { q: "지친 날 친구가 부탁을 해올 때 나의 선택은?", a: "투덜대며 들어줌", b: "단호하게 거절" },
    { q: "다이어트 중 연인 야식 제안, 너는?", a: "같이 무너지자", b: "나만 참는다" },
    { q: "이상형과 매일 싸운다면, 그래도 만날까?", a: "맞춰간다", b: "갈아탄다" },
    { q: "출근 인사, 너의 스타일은?", a: "끝까지 끌어안기", b: "깔끔하게 손 인사" },
    { q: "더 마음이 가는 장소는?", a: "활기찬 노래방", b: "활기찬 운동장/공원" },
    { q: "연인 땀 냄새, 너는?", a: "솔직히 말한다", b: "데오도란트 선물" },
    { q: "내가 부모라면, 받고 싶은 선물 스타일은?", a: "실용적 현금 봉투", b: "직접고른 선물" },
    { q: "가족에게 들으면 섭섭하고 싫은 말은?", a: "너 예민해", b: "그럴 줄 알았다" },
    { q: "바빠서 뜸했던 연인이 연락 오면?", a: "반갑다", b: "서운하다" },
    { q: "일요일 저녁 월요병 오면 나는?", a: "유튜브로 도피", b: "일찍 자려 노력" },
    { q: "작년 반팔 안 맞을 때 너는?", a: "옷이 줄었다 우김", b: "쿨하게 사이즈업" },
    { q: "엄마 사진 또 흔들렸어, 너는?", a: "찍는 법 알려드리기", b: "그냥 받고 넘기기" },
    { q: "갑자기 1억이 생긴다면 어디에 쓸?", a: "빚 청산 & 장비빨", b: "재테크 & 창업" },
    { q: "어느 쪽이 덜 불편해?", a: "방귀 = 노크 소리", b: "방귀 = 장미향" },
    { q: "지금 나를 더 잘 표현하는 말은?", a: "여전히 성장 중", b: "성숙한 지금" },
    { q: "부모님과 에어컨 협상이면?", a: "참고 선풍기", b: "몰래 에어컨" },
    { q: "데이트 사진 보정, 우리는?", a: "보정은 셀프 케어", b: "있는 그대로가 진리" },
    { q: "딸이 있어서 정말 든든하다고 느낄 때는?", a: "센스 있는 선물", b: "조용한 위로" },
    { q: "어느 쪽이 더 나아?", a: "국물 없는 음식만", b: "국물 있는 음식만" },
    { q: "여름 밤 적정 온도 너는?", a: "22도 냉동실파", b: "26도 적정파" },
    { q: "가치관 다른 동료와 해결법은?", a: "쟁점 논쟁", b: "다름 인정" }
  ],
  en: [
    { q: "What kind of coworker do you want to work closely with?", a: "Slacker", b: "Vanishing act" },
    { q: "Watching together on a streaming app — your pick?", a: "binge a romance series", b: "one clean action movie" },
    { q: "If your sibling reads your old diary, you...", a: "snatch it and hide it", b: "read along and laugh" },
    { q: "When your parents try a delivery app for the first time?", a: "help them through it", b: "let them figure it out" },
    { q: "After regretting late-night snacking the next morning?", a: "Swear never again", b: "Know I'll do it again" },
    { q: "What do you usually do first when you see unfamiliar food?", a: "Take a photo right away", b: "Sniff it immediately" },
    { q: "What's your go-to cure when you're feeling terrible?", a: "Take meds, sleep lots", b: "Order yummy food" },
    { q: "Do you think we can make long-distance work?", a: "We can do it", b: "I'm worried" },
    { q: "When you get hungry during a date, what do you do?", a: "Say it honestly", b: "Hold it in and focus" },
    { q: "Telling your partner you want alone time?", a: "say it directly", b: "hint at it gently" },
    { q: "Mom starts old stories in front of guests?", a: "Smile and play along", b: "Escape to my room" },
    { q: "When figuring out your style, what do you rely on?", a: "feedback from others", b: "my own gut feeling" },
    { q: "What worries you more about parents drinking?", a: "Bad drinking habits", b: "Health decline" },
    { q: "What's your study style during exam week?", a: "Quiet library focus", b: "Cafe study buddies" },
    { q: "If you go solo, which sounds better?", a: "Living alone", b: "Living with pals" },
    { q: "If your partner says 'I'm hungry' on a call, you...", a: "order delivery for them", b: "order and eat together" },
    { q: "Which one would you rather do?", a: "Run a YouTube channel", b: "Run a podcast" },
    { q: "What's the best way to unwind after work?", a: "Urgent meeting link", b: "Casual chat" },
    { q: "Forget your partner's friend's name — you?", a: "Just fess up sorry", b: "Fake knowing it" },
    { q: "When you find early dating photos, you...", a: "reminisce together", b: "look at them alone" },
    { q: "Which chill break feels more tempting now?", a: "Quiet nap", b: "Scroll through shorts" },
    { q: "You broke a shared diet pact — you?", a: "confess right away", b: "play dumb forever" },
    { q: "Delivery flopped — what do you do?", a: "leave a 1-star", b: "quietly ghost the place" },
    { q: "If your partner's cold, what do you do with your jacket?", a: "give it right away", b: "say I'm cold too" },
    { q: "What distracts me more before an important decision?", a: "Nosy acquaintances", b: "Dead WiFi" },
    { q: "Which friend is easier to be around?", a: "mirror = selfie time", b: "music = instant dance" },
    { q: "Which one seems less bad?", a: "Getting lost", b: "Getting pickpocketed" },
    { q: "Does reading philosophy appeal to you more than viral videos?", a: "Philosophy book", b: "Viral videos" },
    { q: "Can't fall asleep — you?", a: "Scroll till you drop", b: "Lights off, tough it out" },
    { q: "When tired and a friend asks a favor, I?", a: "Help while complaining", b: "Firmly refuse" },
    { q: "Mid-diet, partner suggests a late-night snack — you?", a: "Cave in together", b: "I'll stay strong" },
    { q: "Would you still meet up if you fought with your ideal partner every day?", a: "Adjust accordingly", b: "Switch it up" },
    { q: "Saying bye before work — your style?", a: "Long clingy hug", b: "A clean wave goodbye" },
    { q: "Where do you feel most drawn?", a: "Lively karaoke room", b: "Energetic park/field" },
    { q: "Partner's sweat smell — you?", a: "Say it honestly", b: "Gift a deodorant" },
    { q: "As a parent, what gift style would you want?", a: "Cash in an Envelope", b: "A Hand-Picked Gift" },
    { q: "Which family comment stings more?", a: "too sensitive", b: "saw that coming" },
    { q: "When your busy partner finally texts back?", a: "just happy", b: "a bit hurt" },
    { q: "When Sunday-evening Monday-dread hits, you...", a: "escape into YouTube", b: "try to sleep early" },
    { q: "When last year's tee doesn't fit — your move?", a: "Claim it shrunk", b: "Just size up" },
    { q: "Mom shook the phone again — your move?", a: "Teach her how to shoot", b: "Just accept it" },
    { q: "Suddenly have 100M won — where does it go?", a: "clear debts + upgrade", b: "invest + start up" },
    { q: "Which feels less awkward?", a: "Passing gas = knocking", b: "Passing gas = rose scent" },
    { q: "Which phrase best describes me right now?", a: "Still growing", b: "Mature now" },
    { q: "Negotiating AC with your parents — you?", a: "Hold out with the fan", b: "Sneak the AC on" },
    { q: "Editing date photos — your stance?", a: "editing is self-care", b: "raw is the truth" },
    { q: "When do you feel really supported having a daughter?", a: "Cool gifts", b: "Quiet comfort" },
    { q: "Which one sounds better?", a: "No broth dishes only", b: "Only broth dishes" },
    { q: "Your ideal AC temp at night?", a: "22°C freezer mode", b: "26°C moderate setting" },
    { q: "Handling a clashing coworker?", a: "Debate the Issue Head-On", b: "Agree to Disagree" }
  ]
};
